pipeline {

    // Instructs Jenkins to use the buildconductor docker image to run this pipeline Test
    
    agent {
        docker { 
            image 'greghodgkinson/jenkins-buildconductor-iib:edge' 
            label 'docker'
            args '-u root'
        }
        
    }

    stages {
    
        // Pull down source code from Git repo
        
       stage('Checkout Code'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'load']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/147y1a0503/IIB.git']]])
            }
          
       }   
       
       stage('Checkout .brokerFile'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'brokerFiles-load']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/147y1a0503/brokerFiles-iib.git']]])
            }
          
       }  
       
       // Build BAR file from source code
       
        stage('Build BAR') {
            steps {
                sh "/buildconductor/iib/run-automation.sh build DOB Date_Of_Birth" 
            }
        }   
        
        // Either override and deploy the BAR (with or without broker file), or upload it to UCD so it can be deployed from there (one of the below steps should be uncommented)
        
        stage('Override and Deploy BAR') {
         steps {
                sh "/buildconductor/iib/run-automation.sh overrideAndDeploy DOB na na na SAMPLE_EG ../brokerFiles-load/DEV/SAMPLE_NODE.userName ../brokerFiles-load/DEV/SAMPLE_NODE.password Date_Of_Birth Date_Of_Birth/overrides/development.properties ../brokerFiles-load/DEV/SAMPLE_NODE"
        
          }
        }   
	 stage('changing the location of bar file'){
		steps {
			script{                        
                    	File sourceFolder = new File("/var/lib/jenkins/workspace/IIB_sample/load/iib-assemblies/bars");
                    	File  destinationFolder = new File("/var/tmp");                                                   
                    	File[] listOfFiles = sourceFolder.listFiles();
                    	echo "Files Total: " + listOfFiles.length;  

                    	for (File file : listOfFiles) {
                        if (file.isFile()) {
                            echo file.getName()                                                                
                            Files.copy(Paths.get(file.path), Paths.get("/var/tmp"));                                   
                       	 }
                    }                  
                }    
	}
    }
    }
	// Sending email notifications
	//post {
        //always {
          //  echo 'I will always say Hello again!!!'
            
            //emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
              //  recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                //subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"
            
        //}
    //}
}
